# Generated by Django 4.2.6 on 2023-10-08 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinPrices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=250)),
                ('price', models.FloatField()),
                ('open_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('news_id', models.BigIntegerField()),
                ('title', models.TextField()),
                ('summary', models.TextField()),
                ('ticker', models.CharField(max_length=50)),
                ('news_date', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reddit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_id', models.BigIntegerField()),
                ('title', models.TextField()),
                ('date', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sentiments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('score', models.BooleanField()),
                ('resource', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RedditComments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_id', models.BigIntegerField()),
                ('text', models.TextField()),
                ('comment_date', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realcrawlers_api.reddit')),
                ('sentiment_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='realcrawlers_api.sentiments')),
            ],
        ),
        migrations.AddConstraint(
            model_name='reddit',
            constraint=models.UniqueConstraint(fields=('post_id',), name='reddit_postid_uq'),
        ),
        migrations.AddField(
            model_name='news',
            name='sentiment_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='realcrawlers_api.sentiments'),
        ),
        migrations.AddConstraint(
            model_name='redditcomments',
            constraint=models.UniqueConstraint(fields=('comment_id',), name='reddit_comment_uq'),
        ),
        migrations.AddConstraint(
            model_name='news',
            constraint=models.UniqueConstraint(fields=('news_id',), name='news_newsid_uq'),
        ),
    ]
